language: cpp

compiler:
 - clang
 - gcc

env:
  matrix:
    - CONF=debug
    - CONF=release
  global:
    - GITHUB_REPO='miloyip/rapidjson'
    # prepare for 32/64 bit multi-arch support
    - BITS=64
    - secure: "HrsaCb+N66EG1HR+LWH1u51SjaJyRwJEDzqJGYMB7LJ/bfqb9mWKF1fLvZGk46W5t7TVaXRDD5KHFx9DPWvKn4gRUVkwTHEy262ah5ORh8M6n/6VVVajeV/AYt2C0sswdkDBDO4Xq+xy5gdw3G8s1A4Inbm73pUh+6vx+7ltBbk="

before_install:
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update -qq
  - sudo apt-get install -y premake4 valgrind

install: true

before_script:
  - pushd build && premake4 'gmake' && popd

script:
  - make -C build/gmake -f test.make    config=${CONF}${BITS}
  - make -C build/gmake -f example.make config=${CONF}${BITS}
  - pushd bin
  -  ./unittest_${CONF}_x${BITS}_gmake
  - valgrind --leak-check=full --error-exitcode=1 ./unittest_${CONF}_x${BITS}_gmake
  - if [ "$CONF" = "release" ]; then ./perftest_${CONF}_x${BITS}_gmake; fi
  - popd
  - ./build/travis-doxygen.sh;
