language: cpp

compiler:
 - clang
 - gcc

env:
  matrix:
    - config=debug64   config_suffix=debug_x64_gmake
    - config=release64 config_suffix=release_x64_gmake
  global:
    secure: "CR3yKliFhwQLX+Zs1PCRcGej6jr4DIZsCqs9x6J2NN+U9Aow0gd/uiPBho/utgm+/TmSBji5n8FO/J3ORo34q4gC6EebTEaN4gCHNXVlIBJFw9x+Gs/lML5i8F2AoweFJY334OVaOf9qC8ZVJ8Z1nEwxj77fq3gcSLzRU3pIaS8="

before_install:
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update -qq
  - sudo apt-get install -y premake4 valgrind

install: true

before_script:
  - pushd build && premake4 'gmake' && popd

script:
  - make -C build/gmake -f test.make
  - make -C build/gmake -f example.make
  - pushd bin
  - ./unittest_${config_suffix}
  - valgrind --leak-check=full --error-exitcode=1 ./unittest_${config_suffix}
  - if [ "$config" = "release64" ]; then ./perftest_${config_suffix}; fi
  - popd
  - ./build/travis-doxygen.sh;
